### ISSUE TITLE
[bug] some pngs with transparent bg get displayed with white bg in the creation tab

### ISSUE THREAD

**Issue by merchantcoppola** [teia-community/teia-ui#88] opened 2022-05-10 20:09 UTC
some transparent pngs get displayed as if they had no transparency (white bg) in the gallery/creations tab- in the objktpage it works with transparency

exapmles: 

https://teia.art/HarmonicFlowers
https://teia.art/objkt/725451

https://teia.art/maybe_celadoor
https://teia.art/objkt/650013

https://discord.com/channels/908672304236625970/941924554899591229/968606448680583178
https://discord.com/channels/908672304236625970/911983442563039312/936378012918751242

**Comment by melMass** [comment] 2022-05-10 20:18
It would be great if they could come here, I'm almost sure they are not minting on teia.art, we already had a similar report a few weeks ago

<img width="736" alt="Screenshot 2022-05-10 at 22 18 08" src="https://user-images.githubusercontent.com/7041726/167715171-d41698b7-71be-4a9b-a2c0-d71ea278afb3.png">

**Comment by melMass** [comment] 2022-08-09 13:52
Closing as this is not reproducible AFAIK, and the thumbnail logic changed since #113 and should be more robust

**Closed as completed by melMass** 2022-08-09 13:52 UTC
Labels: 🐛 bug, ⛏ minting / ipfs
