### ISSUE TITLE
[feat] Folders/Lists for OBJKTs - grouping OBJKTS and "save for later" lists

### ISSUE THREAD

**Issue by merchantcoppola** [teia-community/teia-ui#237] opened 2023-01-14 17:02 UTC
### Describe the problem

This topic has been in discussion for a long time:
Setting up a decentralised system for grouping objkts would be incredibly powerful and unlock a lot of new features such as:

- a "save for alter" list: users could store OBJKTs for later
- for creators grouping OBJKTs into "collections/series"
- for collectors: organizing the collection in "folders"

### Describe the solution you'd like

for the feature to work, one would need to somehow store lists of OBJKTs.
Since we want to do that decentralised, there are a few options

- using Winlosses IPNS solution for storage: https://ipns.app/about
- jagracars approach: json file on ipfs + smartcontract to edit the folders, file gets repinned everytime there is a chnage to that list
- a mix of the two

Quote Jagracar:

> I think the solution via ipns is cheaper in terms of gas, since is an off-chain solution. The initial idea i had was to create a kind of ipns on-chain. A contract that links a user wallet to a ipfs file with the collections data. Each update of the collection would need an update of the contract to point to the new ipfs file. And the update can only be done by the user. I think the most critical thing is to define a good standard for collections, galleries, etc, that can be used by any platform/marketplace/metaverse gallery, etc/ One could combine the two things together. A smart contract that links tz wallets to ipns. Then each ipns is updated off chain. In this way one would not need to put the ipns link in the tezos profile metadata. Some users might not have a tezos profile.

### Additional context

related issues/topics:
- IPNS website: https://ipns.app/about
 - https://github.com/teia-community/teia-ui/issues/226
 - https://github.com/teia-community/teia-ui/issues/189
 - configurable settings (working doc): https://docs.google.com/document/d/1vYkB_BTwCQIzMPxQuX0EHrBCvjjxPJ-eZEtztN15mGI/edit
 - IPNS manifesto by winloss: https://twitter.com/noFungibleNFT/status/1603674944919175168

**Comment by melMass** [comment] 2023-01-15 22:54
Duplicate of #226

**Closed as completed by melMass** 2023-01-15 22:54 UTC
Labels: 😇 help wanted, 🧪 feature request, 🏰 Infra
