### ISSUE TITLE
[feat] Add an 'objkts i own from this artist’ filter/tab on the creations

### ISSUE THREAD

**Issue by merchantcoppola** [teia-community/teia-ui#221] opened 2022-12-06 23:08 UTC
### Describe the problem

An idea by UFFFD on discord from some time ago:
Having a tab in an artists profile for "pieces i own of this artist" or a Filter for that in the creations page

### Describe the solution you'd like

A filter on the "creations tab" 
![filter](https://user-images.githubusercontent.com/97635650/206044242-043b0a7b-acf9-4c42-bff8-3871532573a3.JPG)

### Alternatives considered

a tab next to the "creations tab"

**Comment by melMass** [comment] 2022-12-07 11:15
Duplicate of #59 closing

**Closed as not planned** 2022-12-07 11:16 UTC
Labels: 🧪 feature request
